backend/handlers/csp_prod.go, backend/handlers/csp_staging.go
We no longer have a mailing list form, so this is not necessary.
=> Removing CSP policies for mailing list

backend/handlers/recent_entries_test.go
If you look at the test results you will find out, that 3 entries were filtered.
I fixed the test and it runs green.
=> Fix recent order test

backend/handlers/static.go
Adjusting the logic in static.go so that there are fewer nested ifs and fallthroughs
Also changing the parameter name from rw to w for consistency with the rest of the code.
=> Refactoring and tweaking logic in static.go

backend/handlers/handlers_test.go, backend/handlers/static.go
=> Making ./frontend/dist a const instead of a magic string

.circleci/config.yml
Backend tests can now run without building frontend
=> Updating Circle CI dependencies

frontend/jest.config.js, frontend/package-lock.json, frontend/package.json, frontend/src/store.js, frontend/tests/unit/.eslintrc.js, frontend/tests/unit/store.spec.js, frontend/tests/unit/views/Recent.spec.js
This PR closes #279 
I added the Jest Vue plugin which includes Vue test utils. Jest is a fully-featured Javascript unit testing framework that is very pleasant to work with. Vue Test Utils provides a number of features for testing Vue, Vue-Router and Vuex. 
More info:
https://jestjs.io/
https://vue-test-utils.vuejs.org/
I added some basic tests to the `mutations` in the Vuex store, as a small refactor I moved the mutations into their own exported module to make them more easily testable. 
I also added a unit test for the `Recent` view to assert that it displays the entries in the Vuex store.
=> Unit Testing Setup

frontend/tests/unit/store.spec.js, frontend/tests/unit/views/Recent.spec.js
Making the data better match real data and reducing use of constants.
=> Refactoring frontend unit tests

go.mod, go.sum
It's useful for VS Code. I'm not sure why it needs to be added to the repo, but I'm not that interested in diving into the details right now. Maybe we can take it out later.
=> Adding gopls to the modules

backend/handlers/handlers.go, backend/handlers/submit.go, backend/handlers/validate/entry_date.go, backend/handlers/validate/entry_date_test.go
This moves the validateEntryDate to a separate package and adds unit tests for the date.
=> Moving entry date validation and adding tests

CONTRIBUTING.md
=> Removing TODO about configuring builds on PRs

backend/handlers/csp_common.go, backend/handlers/csp_prod.go, backend/handlers/csp_staging.go
CSP just broke due to changes in dependencies. Taking this as an opportunity to refactor the CSP code and eliminate all the redundancy and less-secure settings.
=> Updating CSP

e2e/docker-compose.yml
95% of the time, it's too much spew to read
=> Trimming Cypress debug output

e2e/docker-compose.yml, integration/docker-compose.yml
Switching browser to Chrome now that it supports video recording.
=> Upgrading Cypress to 3.5.0

.gitignore, docker-compose.yml
Also updates the .gitignore to get rid of stale files.
=> Changing redis to persist data on a shared host volume

frontend/src/controllers/LoginState.js, frontend/src/controllers/UserKit.js, frontend/src/views/Login.vue, frontend/src/views/Logout.vue
_Continuation of https://github.com/mtlynch/whatgotdone/pull/355 in a clean branch. Cherry-picked my commits on top of current `master` for a clean look at the changes._
---
Initially, I was able to reproduce [this issue](https://github.com/mtlynch/whatgotdone/pull/355#issuecomment-548182168), but after cleaning things up, I'm no longer seeing it.
Things I did outside of these commits:
- Deleted `docker-secrets.env`
- Deleted my `.env.development.local` file to make sure everything was using the dummy app-id.
- Retested with a real app-id in `.env.development` and a real app-secret-key in `docker-compose.yaml`
=> Move UserKit code into separate module

e2e/cypress/integration/spec.js, frontend/package-lock.json, frontend/package.json, frontend/src/main.js, frontend/src/views/ViewEntry.vue
=> Adding tweet button to posts for author

frontend/src/App.vue, frontend/src/main.js, frontend/src/views/ViewEntry.vue
The root issue was CSP, so fixing the CSP configuration
=> Removing font-awesome force-height workaround

frontend/src/views/Home.vue
=> Switching landing page screentshots to grid layout

frontend/src/controllers/Recent.js, frontend/src/views/Recent.vue
Appending to recentEntries store only if the new entry key is unique
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/whatgotdone/449)
=> Check for existing keys when appending entries to store.recentEntries

.gcloudignore, README.md
=> Updating README to remove references to e2e tests

frontend/src/controllers/UserKit.js
Checking `UserKitWidget.isInitialized` before resolving the `loadUserKit` Promise.
=> Add check for `UserKitWidget.isInitialized`

backend/datastore/datastore.go, backend/datastore/firestore/entries.go, backend/handlers/google_analytics.go, backend/handlers/google_analytics_test.go, integration/cypress/integration/publish_entry_spec.js
=> If an entry was published recently, display a view count of 1

frontend/src/views/EditEntry.vue, integration/cypress/integration/entry_draft_spec.js
=> Don't save a draft until we've synced the old copy with the server

frontend/src/controllers/LoginState.js, frontend/src/store.js, frontend/src/views/UserProfile.vue
I suspect the reason we're seeing flaky integration test results for the follow feature is that we're not using mutations that Vue can easily track.
=> Change semantics of followed user tracking in vuex store

frontend/src/assets/css/light.css, frontend/src/components/NavigationBar.vue, frontend/src/main.js, frontend/src/views/EditEntry.vue, frontend/src/views/Home.vue
Here's an alternative look and feel for WhatGotDone! 
- I kept it as noninvasive as possible (one css file, overriding existing styles).
- I kept the original colours.
- I kept the mobile responsiveness in mind.
This is my first PR to a public repo * ever *. It was tons of fun. No stress if you don't like it!
Screenshots:
_Landing page_
_Plain-text editor_
_Rich-text editor_
_Recent entries_
_Viewing an entry_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mtlynch/whatgotdone/568)
=> Change to light UI theme

frontend/src/views/Home.vue
Delete old rules and fix the buttons on the jumbotron so they're not on top of each other on mobile.
=> Clean up CSS on homepage

frontend/src/views/UserProfile.vue, frontend/src/views/ViewEntry.vue
They're too unwieldy. It's better to do margins or flexbox.
=> Remove instances of float CSS rules

.circleci/config.yml
Reverts mtlynch/whatgotdone#613
=> Revert "Update deploy image to gcloud 351 slim"

dev-scripts/git-hooks/pre-commit, dev-scripts/run-go-tests
Also adds a quick mode to skip them in pre-commit hooks because they're kind of slow.
=> Add race condition check to Go tests

frontend/src/controllers/Avatar.js, frontend/src/controllers/Common.js, frontend/src/controllers/Drafts.js, frontend/src/controllers/Entries.js, frontend/src/controllers/Follow.js, frontend/src/controllers/Logout.js, frontend/src/controllers/Media.js, frontend/src/controllers/Preferences.js, frontend/src/controllers/Reactions.js, frontend/src/controllers/User.js
And change it to the non-default export.
This sets the stage for other common functions I want to add.
=> Move CsrfToken.js to Common.js

integration/cypress/integration/entry_draft_spec.js, integration/cypress/integration/entry_template_spec.js
And delete one unused references to it.
=> Fix the name of postPreferences in integration tests

integration/cypress/integration/entry_draft_spec.js, integration/cypress/integration/entry_template_spec.js, integration/cypress/integration/follow_spec.js, integration/cypress/integration/login_spec.js, integration/cypress/integration/publish_entry_spec.js, integration/cypress/integration/reactions_spec.js, integration/cypress/integration/user_profile_spec.js
cy.route is deprecated and can't catch calls to the fetch API.
=> Change cypress to use cy.intercept instead of cy.route

frontend/package-lock.json, frontend/package.json
Previous refactorings have replaced it with the fetch API
=> Remove axios dependency

backend/datastore/datastore.go, backend/datastore/firestore/reaction.go, backend/handlers/reactions.go, backend/handlers/reactions_test.go, backend/handlers/routes.go, frontend/src/components/Reactions.vue, frontend/src/controllers/Reactions.js
Delete via HTTP DELETE as opposed to the old way of POSTing an empty reaction.
=> Add proper deletion for entry reactions

backend/datastore/mock/mock.go, backend/handlers/export.go, backend/handlers/export_test.go, backend/handlers/routes.go, backend/handlers/user.go, frontend/src/controllers/Export.js, frontend/src/views/UserProfile.vue, integration/cypress/integration/export_spec.js
=> Add support for exporting user data as JSON

backend/entries/recent.go
In the previous implementation, we could leak the channel c if we encountered an error retrieving one of the entries because we exit before the WaitGroup completes. This changes the implementation to avoid exiting before the WaitGroup completes so that we still close the channel on error.
=> Refactor Recent method to avoid leaking the channel

backend/handlers/export.go
Apparently, we don't really need to close channels and it's fine to leave them open: https://stackoverflow.com/a/8593986/90388
=> Get rid of logic dedicated to ensuring we close channels

backend/handlers/routes.go, backend/handlers/static.go, frontend/package-lock.json, integration/cypress/integration/reactions_spec.js, integration/cypress/integration/user_profile_spec.js, test-data-manager/integration-data.yaml
Previously we were just returning HTTP 200 for any route and then allowing the frontend to display a 404-ish page, but the backend should return an actual HTTP 404.
=> Check routes more strictly

.circleci/config.yml
Per: https://community.fly.io/t/cant-complete-flyctl-deploy-process-context-deadline-exceeded/2561/13?u=mtlynch
=> Use --local-only flag when deploying to fly.io

dev-scripts/serve
Change the behavior of the serve script so that it only wipes and rewrites the local DB if no DB already exists.
=> Change dev serve script to conditionally repopulate the DB

dev-scripts/download-prod-db
Add a dev-script that download the SQLite database from the live, production server and uses it as the local database.
=> Add a convenience script to download the production DB locally

.circleci/config.yml
xlarge instances take too long to provision
=> Reduce integration machine size to medium

frontend/src/components/Journal.vue, frontend/src/components/JournalBody.vue, frontend/src/components/ProjectEntry.vue, frontend/src/views/ViewProjectPage.vue
This fixes the style on the projects view and reduces redundant code between the project entry and regular journal entries
=> Refactor JournalBody into its own component

dev-scripts/run-go-tests
Update staticcheck
Refactor flags
=> Update run-go-tests script

frontend/vue.config.js
Changed in webpack 4 apparently
=> Change disableHostCheck to allowedHost

flake.nix
Credit to [/u/Strum355](https://www.reddit.com/user/Strum355) on reddit for their assistance: https://www.reddit.com/r/NixOS/comments/15d874l/trying_to_create_a_nix_flake_for_go_with_static/ju2wwkj/
=> Enable static Go linking in dev shell

dev-scripts/serve-backend
Adjust flags for serve-backend script so it works in a Nix environment.
=> Fix serve-backend under Nix

frontend/public/index.html, frontend/src/components/JournalHeader.vue, frontend/src/components/PartialJournal.vue, frontend/src/components/ProjectEntry.vue, frontend/src/controllers/Entries.js, frontend/src/controllers/Recent.js, frontend/src/views/EditEntryPage.vue, frontend/src/views/ViewEntryPage.vue
Reverts mtlynch/whatgotdone#913
=> Revert "Add custom element for entry date"

docker_entrypoint
=> Fix stray -v in litestream command
