mtlynch/whatgotdone

frontend/src/components/Journal.vue
frontend/src/components/JournalPreview.vue
frontend/src/components/PartialJournal.vue

ugc is more appropriate because it's user-generated content
Reference: https://support.google.com/webmasters/answer/96569?hl=en

Changing link rel from nofollow to ugc

---

backend/handlers/static.go

Otherwise the server response fails to set the proper Content-Type header

Switching to http.ServeFile

---

frontend/src/components/Journal.vue
frontend/src/components/JournalPreview.vue
frontend/src/components/PartialJournal.vue

Otherwise, on mobile, text can cause the entire page to scroll

Setting journal entries to scroll on overflow

---

frontend/src/components/Journal.vue
frontend/src/components/JournalPreview.vue
frontend/src/components/PartialJournal.vue

Didn't realize that I was accidentally adding scrollbars *everywhere* on Desktop. Changing overflow to auto on mobile and visible (default) on Desktop

Fixing scrollbars

---

e2e/cypress/integration/spec.js
frontend/src/views/EditEntry.vue
frontend/src/views/ViewEntry.vue

This makes it possible for the user to delete previously published updates.

Allow the user to publish updates with no content

---

.circleci/config.yml

Forked pull requests don't have access to secret environment variables, so e2e tests will always fail. Add a step to automatically skip the e2e step on forked PRs, so we can at least run the unit tests.

Skip e2e tests on forked pull requests

---

frontend/src/components/JournalHeader.vue
frontend/src/components/PartialJournal.vue

The journal elements should remain centered even if parent elements are left-aligned

Fixing alignment in journal header

---

backend/datastore/datastore.go
backend/datastore/firestore/close.go

It turns out that nothing was actually ever calling this method. We don't need it because we never have to close the connection to the datastore.

Removing Close method from datastore

---

e2e/cypress/integration/spec.js

This is a temporary workaround to prevent the Too Many Requests errors we're seeing in UserKit. When we switch to the dev app ID, this should go away.

Adding a delay into the e2e test

---

backend/handlers/csp_common.go

It turns out that Google expects this directive for reCaptcha and we were missing it.
https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website.-how-can-i-configure-it-to-work-with-recaptcha

Adding frame-src to CSP

---

backend/handlers/recent_entries.go
backend/handlers/recent_entries_test.go

Changing behavior of /api/recentEntries so that it returns an empty array instead of null when the datastore is empty.

/api/recentEntries should return [] on empty datastore

---

e2e/cypress/integration/spec.js

After the user signs out, the 'Account' dropdown should no longer be visible.

Specify in log in / log out e2e test that Account dropdown disappears

---

frontend/vue.config.js

This doesn't really do anything useful, and it inhibits useful dev scenarios like developing on a remote VM

Disabling host check in Vue dev mode

---

.circleci/config.yml

It fails with bad permissions but works deploying locally.

Removing cron job deploy from Circle CI

---

frontend/src/views/Home.vue

This achieves consistency with other h2 elements on the site.
Fixes #401

Changing h2 elements to use sentence-case capitalization

---

frontend/src/views/Home.vue

Narrowing the 'Contact Us' section of the home page so that it lines up a little better with text from the previous sections.
Fixes #402

Narrowing the last section of the home page

---

frontend/src/components/NavigationBar.vue

It's confusing to show the user both a 'Publish' button and a 'Post Update' button, so hide 'Post Update' in the navbar if the user is already editing an update.
Fixes #404

Hide 'Post Update' button if the user is on the entry edit page

---

frontend/src/views/EditEntry.vue
integration/cypress/integration/spec.js

The edit entry page was redirecting the user to /login, but this was breaking the back button. Fix is to just do .replace() instead of .push()
Fixes #405

Preventing break of the back button on login page

---

frontend/src/controllers/UserKit.js
integration/cypress/integration/spec.js

Per @dtq's comment on #406, we actually want to remove the data-login-dismiss = false line because it's making the login window un-dismissable.
Fixes #406

Adjusting UserKit widget params to allow exiting the modal

---

frontend/src/views/EditEntry.vue

Otherwise, we risk unexpectedly taking the user away from their page mid-edit and losing it before the draft saves.

Adding target="_blank" to Markdown link

---

backend/handlers/csp_common.go
backend/handlers/csp_dev.go

Workaround because we can't seem to make Google Auth sign in work otherwise: https://gist.github.com/mtlynch/f364b61a215bd1cf9ab7ac61d70a47f6

Adding unsafe-inline to style-src

---

app.yaml

Adding a wildcard handler to app.yaml to ensure that What Got Done always redirects clients to HTTPS in production.

Adding handlers wildcard to app.yaml to ensure HTTPS always

---

frontend/src/views/ViewEntry.vue

In #423, I meant to hide the reaction buttons when the author is viewing their own entry, but I accidentally hid the reaction buttons *and* the reactions themselves.
This change brings back both the reaction buttons and the reaction history until I find a cleaner way to hide the buttons in author mode.

Bringing back reactions in author mode

---

frontend/src/controllers/Recent.js
frontend/src/views/Recent.vue

Added code to prevent duplicate user clicks when more entries get request is in progress. 
Button will be disabled when user hit More entries button and it will be enabled when get request is completed.

Disabled "More Entries" button when get request is in progress

---

e2e/cypress.json
integration/cypress.json

It just adds extra time to the build and we don't care that much about saving file size

Disabling video compression

---

.circleci/config.yml
backup-service/README.md
backup-service/cron.yaml
backup-service/package.json
cron.yaml

It turns out they're per-app, not per-service, so they were overwriting each other.

Unifying cron.yaml files into a single file

---

backend/handlers/draft.go
backend/handlers/entries.go
backend/handlers/google_analytics.go
backend/handlers/logout.go
backend/handlers/project.go
backend/handlers/reactions.go
backend/handlers/routes.go
backend/handlers/user.go

I should have thought of this earlier, but we don't need to independently define no-op functions for every route.

Refactoring OPTIONS handlers of backend router

---

frontend/package-lock.json
frontend/package.json
frontend/src/main.js

Now that we do all axios calls in controllers, we no longer need vue-axios

Removing vue-axios

---

e2e/cypress/integration/spec.js

We're getting rid of e2e tests a they're either redundant or depend on external state. This is the first wave of cuts to get rid of tests that are covered in ./integration.

Deleting e2e tests that are redundant to integration tests

---

frontend/src/App.vue

If users is not logged in to UserKit, we should clear the login state. Otherwise, we should refresh the login details from the server.

Actually clear login state

---

frontend/src/App.vue
frontend/src/router.js
integration/cypress/integration/login_spec.js

If the What Got Done's store thinks the user is logged in, but UserKit says they're not, they'll end up in a weird state where they stay on a page they're not authenticated to interact with. This adds a check after the UserKit authentication to redirect the user to login if they need authentication on the given page.

Check if authentication is required after checking login state

---

frontend/src/components/Journal.vue
frontend/src/components/JournalPreview.vue
frontend/src/components/PartialJournal.vue

Added scoped css to display no bullets for task lists.
Fixes #434 
---
*Tip*: If you add the above "Fixes ..." line to your PR description, it automatically closes the bug when the PR is merged.

Task list shouldn't show bullet points next to check box #434

---

integration/cypress/integration/login_spec.js

We never left the /entry/edit route, so we're likely running through the test too quickly and confusing login state.

Fix flakiness in login_spec

---

backend/handlers/draft.go
backend/handlers/entries.go
backend/handlers/follow.go
backend/handlers/preferences.go
backend/handlers/reactions.go
backend/handlers/user.go
test-data-manager/server.go

The frontend never actually checks it, so it's unnecessary. In cases where it's the only part of the response, it's fine to just return an HTTP 200 OK with an empty body.

Remove Ok field from backend responses

---

frontend/src/views/EditUserProfile.vue

Switch to ml-auto instead of float-right, as float-right was causing it to sit on top of the horizontal rule element following it.

Fix save button on edit screen so it doesn't collide with hr

---

frontend/src/App.vue

Previous rule was too broad and included non-text links.

Narrow CSS rule for text color

---

backend/gcs/upload.go
backend/handlers/media.go

We need this in a future PR to support cache control policies other than 'public', which is GCS's default.

Add support for Cache-Control in gcs.UploadFile

---

.circleci/config.yml
backend/handlers/csp_common.go

Waiting for GCS to update certificates for:
https://media.whatgotdone.com/avatars/michael/michael-avatar-300px.jpg
Then:
```bash
cd $(mktemp -d) && \
gsutil -m cp -r \
"gs://whatgotdone-public/avatars/" \
"gs://whatgotdone-public/uploads/" \
. && \
gsutil -m cp -r uploads gs://media.whatgotdone.com/ && \
gsutil -m cp -r avatars  gs://media.whatgotdone.com/
```

Switch media to media.whatgotdone.com bucket

---

frontend/package-lock.json
frontend/package.json

Bootswatch 5.0.0 depends on bootstrap 5, which What Got Done is not yet ready for

Downgrade bootswatch back to 4.6.0

---

frontend/src/App.vue
frontend/src/views/ViewEntry.vue

The view entry page doesn't need an extra container, and we can use b-container to take advantage of bootstrap-vue features.

Adjust containers in frontend

---

integration/cypress.json
integration/cypress/plugins/index.js

It's too much of a gotcha that the cypress.json file ignores it in case we ever add one during testing/debugging.

Add empty Cypress plugins file

---

backend/handlers/draft.go
backend/handlers/entries.go
backend/handlers/follow.go
backend/handlers/google_analytics.go
backend/handlers/media.go
backend/handlers/preferences.go
backend/handlers/project.go
backend/handlers/reactions.go
backend/handlers/recent_entries.go
backend/handlers/respond.go
backend/handlers/user.go

Refactor all the HTTP handlers that return JSON data to use a common handler function, respondOK, which abstracts away the details of the encoding.
Also, switches to anonymous structs for data types that are only used once.

Refactor JSON handlers to use common response method

---

backend/handlers/entries.go

Remind the reader that publishing the entry also updates the associated draft for that entry.

Add comment to entries handler

---

backend/handlers/google_analytics.go
backend/handlers/google_analytics_test.go

We were validating pageviews in too complicated a way. We can simplify it by just checking whether there's a journal entry associated with the URL path.

Simplify validation for pageview paths

---

backend/datastore/datastore.go
backend/datastore/firestore/user.go
backend/handlers/user.go

Previously, it was limited to users who have published entries. This expands the function to include users who have saved preferences, saved a draft entry, or saved profile information.
Notably, this leaves out users who haven't interacted with What Got Done or whose only interaction is following other users or reacting to posts.

Change the behavior of datastore.Users to include more users

---

backend/datastore/firestore/user.go

Retrieve the keys of the collection rather than trying to parse the document.

Fix firestore query for usernames

---

integration/cypress/integration/rich_text_editor_spec.js

As of the latest version, it's no longer necessary.
Fixes #574.

Remove tiptap test workaround

---

backend/datastore/sqlite/page_views.go

It creates too much log spew every few minutes.

Remove log message about saving pageviews

---

frontend/src/controllers/Media.js

Apparently the browser will set it automatically, and us setting it explicitly messes things up.

Remove content-type header from Media controller

---

backend/datastore/datastore.go
backend/datastore/mock/mock.go
backend/datastore/sqlite/page_views.go
backend/handlers/google_analytics.go
backend/handlers/google_analytics_test.go
backend/handlers/routes.go

Previously, we relied on an external process to call /api/tasks/refreshGoogleAnalytics periodically. This was a naive approach and required us to refresh analytics and do a lot of datastore writes even when nobody was viewing the site for hours.
This implementation refreshes stats if someone requests pageview stats and it has been more than 3 minutes since the last refresh. Note that it updates it for the next request; the current request will get the stale data, but that's okay, as we assume pageview stats don't change *that* much in a few minutes.

Update Google Analytics data automatically

---

backend/main.go

In production, we run What Got Done behind a proxy, so we should process the proxy headers properly. Otherwise, it looks like all requests are coming from the proxy server.

Configure gorilla logging to process proxy headers

---

backend/main.go

This seems to cause PUT and POST requests to fail with `Forbidden - referer invalid`
This reverts commit fbaf256996560639f2e1b06c915d0d50b9600502.

Revert "Configure gorilla logging to process proxy headers (#718)"

---

backend/handlers/reactions.go

As of 1f06a80, the database does not contain empty reactions, so we don't need to filter for them.

Remove filtering logic for empty reactions

---

litestream.yml

If a snapshot and validation occur at the same time, the validation can incorrectly flag the backups as invalid, so this adds a 13m offset so that they infrequently land on the same time.

Add an offset to validation-interval to offset it from snapshot-interval

---

.circleci/config.yml
dev-scripts/git-hooks/pre-commit
dev-scripts/run-go-tests

Previously, it was slow by default and the user had to pass the --quick flag to make it go fast. Typically, I'll run this script manually during development, so it's easier if the default is fast and we configure CI to run the slower, more comprehensive version.

Make run-go-tests script fast by default

---

dev-scripts/populate-dev-data

It's possible for stray files to be around that leave the DB in a weird state.

Remove DB files before repopulating

---

backend/handlers/draft_test.go
backend/handlers/entries_test.go
backend/handlers/export_test.go
backend/handlers/google_analytics_test.go
backend/handlers/reactions_test.go
backend/handlers/recent_entries_test.go
backend/handlers/user_test.go

This allows the tests to rely less on internal properties of the server.

Use the public Router method for testing handlers

---

backend/datastore/sqlite/draft.go
backend/handlers/draft_test.go

Instead of using a mock datastore, it's better to test with the real SQLite datastore implementation. We use the :memory: path to ensure the DB stays in memory and doesn't persist across tests.

Switch draft handler tests to use real datastore

---

backend/datastore/test_sqlite/db.go
backend/handlers/draft_test.go
backend/handlers/user_test.go
backend/random/string.go

Having multiple tests use :memory: can cause Go to reuse the database across tests. Using a random filename preserves the in-memory behavior without the risk of cross-test contamination.

Use a test implementation of datastore in tests

---

.circleci/config.yml
.gitignore
Dockerfile
README.md
backend/gcp/service_account_dev.go
backend/gcp/service_account_prod.go
backend/gcp/service_account_staging.go
docker-compose.yml

docker-compose unintentionally had a dependency on the existence of GCP service account secrets, which are actually optional. This fixes docker-compose so that it can run even if GCP service account credentials are not present on the filesystem.

Make GCP creds option for docker-compose

---

.circleci/config.yml
.dockerignore
.gitignore
Dockerfile
creds/README.md
docker-compose.yml

Fixes a regression caused by 0c8400db762a2efae0286a15bbddbb37c2cc7124 that prevented production builds from keeping GCP creds and using GCS buckets.

Build credentials folder into Docker container

---

.circleci/config.yml

It doesn't seem to serve a purpose and just burns time.

Don't upload e2e-results to CI

---

dev-scripts/serve-frontend
frontend/package.json

It's just more complicated to go through npm when we can avoid it.

Get rid of npm serve script

---

modd.conf

Otherwise, build failures don't show up in the console logs.

Show build output in modd

---

frontend/src/views/PrivacyPolicyPage.vue

We don't do any marketing or share info with marketers, so there shouldn't be language there.

Trim extraneous information from privacy policy

---

.env.example
dev-scripts/serve-frontend
frontend/.env.dev

It now is just the root .env.dev file which isn't in source control

Get rid of frontend/.env.dev
